# Generated by Django 5.0.6 on 2024-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
