# Generated by Django 5.0.6 on 2024-08-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_card_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='board.list')),
            ],
        ),
    ]
