# Generated by Django 5.0.6 on 2024-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_bio'),
        ('board', '0006_remove_list_is_completed_card_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_boards', to='account.customuser'),
        ),
    ]
