# Generated by Django 5.0.6 on 2024-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To-Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20),
        ),
    ]
