# Generated by Django 5.0.6 on 2024-08-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_bio'),
        ('board', '0011_board_color_alter_board_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='board.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='account.customuser')),
            ],
        ),
    ]
