# Generated by Django 5.0.6 on 2024-08-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cards', to='board.member'),
        ),
    ]
