# Generated by Django 5.0.6 on 2024-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_remove_card_assigned_members_card_assigned_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
