# Generated by Django 5.1.2 on 2024-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_card_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_cards', to='board.member'),
        ),
    ]
